{
    "primaryDatasource": "", 
    "dataSourceList": [
        {
            "numRows": 0, 
            "fieldList": [], 
            "name": "Parameters", 
            "datasourceCaption": "Parameters", 
            "fieldIconRes": "datasource"
        }, 
        {
            "numRows": 0, 
            "fieldList": [
                {
                    "fieldRole": "dimension", 
                    "fieldIconRes": "geographic", 
                    "defaultFieldRole": "dimension", 
                    "description": "Area Code", 
                    "aggregation": "none", 
                    "defaultAggregation": "sum", 
                    "fieldType": "ordinal", 
                    "type": "column", 
                    "defaultFieldType": "ordinal", 
                    "fn": "[Sample - Coffee Chain (Access)].[Area Code]", 
                    "name": "Area Code"
                }, 
                {
                    "fieldRole": "measure", 
                    "fieldIconRes": "number-quant", 
                    "defaultFieldRole": "measure", 
                    "description": "Budget COGS", 
                    "aggregation": "none", 
                    "defaultAggregation": "sum", 
                    "fieldType": "quantitative", 
                    "type": "column", 
                    "defaultFieldType": "quantitative", 
                    "fn": "[Sample - Coffee Chain (Access)].[Budget COGS]", 
                    "name": "Budget COGS"
                }, 
                {
                    "fieldRole": "measure", 
                    "fieldIconRes": "number-quant", 
                    "defaultFieldRole": "measure", 
                    "description": "Budget Margin", 
                    "aggregation": "none", 
                    "defaultAggregation": "sum", 
                    "fieldType": "quantitative", 
                    "type": "column", 
                    "defaultFieldType": "quantitative", 
                    "fn": "[Sample - Coffee Chain (Access)].[Budget Margin]", 
                    "name": "Budget Margin"
                }, 
                {
                    "fieldRole": "measure", 
                    "fieldIconRes": "number-quant", 
                    "defaultFieldRole": "measure", 
                    "description": "Budget Profit", 
                    "aggregation": "none", 
                    "defaultAggregation": "sum", 
                    "fieldType": "quantitative", 
                    "type": "column", 
                    "defaultFieldType": "quantitative", 
                    "fn": "[Sample - Coffee Chain (Access)].[Budget Profit]", 
                    "name": "Budget Profit"
                }, 
                {
                    "fieldRole": "measure", 
                    "fieldIconRes": "number-quant", 
                    "defaultFieldRole": "measure", 
                    "description": "Budget Sales", 
                    "aggregation": "none", 
                    "defaultAggregation": "sum", 
                    "fieldType": "quantitative", 
                    "type": "column", 
                    "defaultFieldType": "quantitative", 
                    "fn": "[Sample - Coffee Chain (Access)].[Budget Sales]", 
                    "name": "Budget Sales"
                }, 
                {
                    "fieldRole": "measure", 
                    "fieldIconRes": "number-quant", 
                    "defaultFieldRole": "measure", 
                    "description": "COGS", 
                    "aggregation": "none", 
                    "defaultAggregation": "sum", 
                    "fieldType": "quantitative", 
                    "type": "column", 
                    "defaultFieldType": "quantitative", 
                    "fn": "[Sample - Coffee Chain (Access)].[COGS]", 
                    "name": "COGS"
                }, 
                {
                    "fieldRole": "dimension", 
                    "fieldIconRes": "date", 
                    "defaultFieldRole": "dimension", 
                    "description": "Date", 
                    "aggregation": "none", 
                    "defaultAggregation": "year", 
                    "fieldType": "ordinal", 
                    "type": "column", 
                    "defaultFieldType": "ordinal", 
                    "fn": "[Sample - Coffee Chain (Access)].[Date]", 
                    "name": "Date"
                }, 
                {
                    "fieldRole": "measure", 
                    "fieldIconRes": "number-quant", 
                    "defaultFieldRole": "measure", 
                    "description": "Inventory", 
                    "aggregation": "none", 
                    "defaultAggregation": "average", 
                    "fieldType": "quantitative", 
                    "type": "column", 
                    "defaultFieldType": "quantitative", 
                    "fn": "[Sample - Coffee Chain (Access)].[Inventory]", 
                    "name": "Inventory"
                }, 
                {
                    "name": "Location_Area Code", 
                    "fieldIconRes": "geographic", 
                    "type": "column", 
                    "aggregation": "none", 
                    "defaultAggregation": "sum", 
                    "fieldType": "ordinal", 
                    "defaultFieldRole": "dimension", 
                    "fieldRole": "dimension", 
                    "isHidden": true, 
                    "defaultFieldType": "ordinal", 
                    "fn": "[Sample - Coffee Chain (Access)].[Location_Area Code]", 
                    "description": "Location_Area Code"
                }, 
                {
                    "fieldRole": "measure", 
                    "fieldIconRes": "number-quant", 
                    "defaultFieldRole": "measure", 
                    "description": "Margin", 
                    "aggregation": "none", 
                    "defaultAggregation": "sum", 
                    "fieldType": "quantitative", 
                    "type": "column", 
                    "defaultFieldType": "quantitative", 
                    "fn": "[Sample - Coffee Chain (Access)].[Margin]", 
                    "name": "Margin"
                }, 
                {
                    "fieldRole": "dimension", 
                    "fieldIconRes": "text", 
                    "defaultFieldRole": "dimension", 
                    "description": "Market", 
                    "aggregation": "none", 
                    "defaultAggregation": "count", 
                    "fieldType": "nominal", 
                    "type": "column", 
                    "defaultFieldType": "nominal", 
                    "fn": "[Sample - Coffee Chain (Access)].[Market]", 
                    "name": "Market"
                }, 
                {
                    "fieldRole": "dimension", 
                    "fieldIconRes": "text", 
                    "defaultFieldRole": "dimension", 
                    "description": "Market Size", 
                    "aggregation": "none", 
                    "defaultAggregation": "count", 
                    "fieldType": "nominal", 
                    "type": "column", 
                    "defaultFieldType": "nominal", 
                    "fn": "[Sample - Coffee Chain (Access)].[Market Size]", 
                    "name": "Market Size"
                }, 
                {
                    "fieldRole": "measure", 
                    "fieldIconRes": "number-quant", 
                    "defaultFieldRole": "measure", 
                    "description": "Marketing", 
                    "aggregation": "none", 
                    "defaultAggregation": "sum", 
                    "fieldType": "quantitative", 
                    "type": "column", 
                    "defaultFieldType": "quantitative", 
                    "fn": "[Sample - Coffee Chain (Access)].[Marketing]", 
                    "name": "Marketing"
                }, 
                {
                    "fieldRole": "dimension", 
                    "fieldIconRes": "text", 
                    "defaultFieldRole": "dimension", 
                    "description": "Product", 
                    "aggregation": "none", 
                    "defaultAggregation": "count", 
                    "fieldType": "nominal", 
                    "type": "column", 
                    "defaultFieldType": "nominal", 
                    "fn": "[Sample - Coffee Chain (Access)].[Product]", 
                    "name": "Product"
                }, 
                {
                    "fieldRole": "dimension", 
                    "fieldIconRes": "text", 
                    "defaultFieldRole": "dimension", 
                    "description": "Product Line", 
                    "aggregation": "none", 
                    "defaultAggregation": "count", 
                    "fieldType": "nominal", 
                    "type": "column", 
                    "defaultFieldType": "nominal", 
                    "fn": "[Sample - Coffee Chain (Access)].[Product Line]", 
                    "name": "Product Line"
                }, 
                {
                    "fieldRole": "dimension", 
                    "fieldIconRes": "text", 
                    "defaultFieldRole": "dimension", 
                    "description": "Product Type", 
                    "aggregation": "none", 
                    "defaultAggregation": "count", 
                    "fieldType": "nominal", 
                    "type": "column", 
                    "defaultFieldType": "nominal", 
                    "fn": "[Sample - Coffee Chain (Access)].[Product Type]", 
                    "name": "Product Type"
                }, 
                {
                    "name": "Product_ProductId", 
                    "fieldIconRes": "number-quant", 
                    "type": "column", 
                    "aggregation": "none", 
                    "defaultAggregation": "sum", 
                    "fieldType": "quantitative", 
                    "defaultFieldRole": "measure", 
                    "fieldRole": "measure", 
                    "isHidden": true, 
                    "defaultFieldType": "quantitative", 
                    "fn": "[Sample - Coffee Chain (Access)].[Product_ProductId]", 
                    "description": "Product_ProductId"
                }, 
                {
                    "name": "ProductId", 
                    "fieldIconRes": "number-quant", 
                    "type": "column", 
                    "aggregation": "none", 
                    "defaultAggregation": "sum", 
                    "fieldType": "quantitative", 
                    "defaultFieldRole": "measure", 
                    "fieldRole": "measure", 
                    "isHidden": true, 
                    "defaultFieldType": "quantitative", 
                    "fn": "[Sample - Coffee Chain (Access)].[ProductId]", 
                    "description": "ProductId"
                }, 
                {
                    "fieldRole": "measure", 
                    "fieldIconRes": "number-quant", 
                    "defaultFieldRole": "measure", 
                    "description": "Profit", 
                    "aggregation": "none", 
                    "defaultAggregation": "sum", 
                    "fieldType": "quantitative", 
                    "type": "column", 
                    "defaultFieldType": "quantitative", 
                    "fn": "[Sample - Coffee Chain (Access)].[Profit]", 
                    "name": "Profit"
                }, 
                {
                    "fieldRole": "measure", 
                    "fieldIconRes": "number-quant", 
                    "defaultFieldRole": "measure", 
                    "description": "Sales", 
                    "aggregation": "none", 
                    "defaultAggregation": "sum", 
                    "fieldType": "quantitative", 
                    "type": "column", 
                    "defaultFieldType": "quantitative", 
                    "fn": "[Sample - Coffee Chain (Access)].[Sales]", 
                    "name": "Sales"
                }, 
                {
                    "fieldRole": "dimension", 
                    "fieldIconRes": "geographic", 
                    "defaultFieldRole": "dimension", 
                    "description": "State", 
                    "aggregation": "none", 
                    "defaultAggregation": "count", 
                    "fieldType": "nominal", 
                    "type": "column", 
                    "defaultFieldType": "nominal", 
                    "fn": "[Sample - Coffee Chain (Access)].[State]", 
                    "name": "State"
                }, 
                {
                    "fieldRole": "measure", 
                    "fieldIconRes": "number-quant", 
                    "defaultFieldRole": "measure", 
                    "description": "Total Expenses", 
                    "aggregation": "none", 
                    "defaultAggregation": "sum", 
                    "fieldType": "quantitative", 
                    "type": "column", 
                    "defaultFieldType": "quantitative", 
                    "fn": "[Sample - Coffee Chain (Access)].[Total Expenses]", 
                    "name": "Total Expenses"
                }, 
                {
                    "fieldRole": "dimension", 
                    "fieldIconRes": "text", 
                    "defaultFieldRole": "dimension", 
                    "description": "Type", 
                    "aggregation": "none", 
                    "defaultAggregation": "count", 
                    "fieldType": "nominal", 
                    "type": "column", 
                    "defaultFieldType": "nominal", 
                    "fn": "[Sample - Coffee Chain (Access)].[Type]", 
                    "name": "Type"
                }, 
                {
                    "name": ":Measure Names", 
                    "fieldIconRes": "text", 
                    "isGenerated": true, 
                    "defaultFieldRole": "dimension", 
                    "aggregation": "none", 
                    "defaultAggregation": "count", 
                    "fieldType": "nominal", 
                    "fieldRole": "dimension", 
                    "type": "column", 
                    "defaultFieldType": "nominal", 
                    "fn": "[Sample - Coffee Chain (Access)].[:Measure Names]", 
                    "description": "Measure Names"
                }, 
                {
                    "name": "Geometry (generated)", 
                    "fieldIconRes": "geographic", 
                    "isGenerated": true, 
                    "isAutoHidden": true, 
                    "aggregation": "none", 
                    "defaultAggregation": "attr", 
                    "isAutoColumn": true, 
                    "fieldType": "nominal", 
                    "defaultFieldRole": "measure", 
                    "type": "column", 
                    "fieldRole": "measure", 
                    "isHidden": true, 
                    "defaultFieldType": "nominal", 
                    "fn": "[Sample - Coffee Chain (Access)].[Geometry (generated)]", 
                    "description": "Geometry"
                }, 
                {
                    "name": "Latitude (generated)", 
                    "fieldIconRes": "geographic-quant", 
                    "isGenerated": true, 
                    "isAutoHidden": true, 
                    "aggregation": "none", 
                    "defaultAggregation": "average", 
                    "isAutoColumn": true, 
                    "fieldType": "quantitative", 
                    "defaultFieldRole": "measure", 
                    "fieldRole": "measure", 
                    "type": "column", 
                    "defaultFieldType": "quantitative", 
                    "fn": "[Sample - Coffee Chain (Access)].[Latitude (generated)]", 
                    "description": "Latitude (generated)"
                }, 
                {
                    "name": "Longitude (generated)", 
                    "fieldIconRes": "geographic-quant", 
                    "isGenerated": true, 
                    "isAutoHidden": true, 
                    "aggregation": "none", 
                    "defaultAggregation": "average", 
                    "isAutoColumn": true, 
                    "fieldType": "quantitative", 
                    "defaultFieldRole": "measure", 
                    "fieldRole": "measure", 
                    "type": "column", 
                    "defaultFieldType": "quantitative", 
                    "fn": "[Sample - Coffee Chain (Access)].[Longitude (generated)]", 
                    "description": "Longitude (generated)"
                }, 
                {
                    "name": "Multiple Values", 
                    "fieldIconRes": "number-quant", 
                    "isGenerated": true, 
                    "defaultFieldRole": "measure", 
                    "aggregation": "none", 
                    "defaultAggregation": "sum", 
                    "fieldType": "quantitative", 
                    "fieldRole": "measure", 
                    "type": "column", 
                    "defaultFieldType": "quantitative", 
                    "fn": "[Sample - Coffee Chain (Access)].[Multiple Values]", 
                    "description": "Measure Values"
                }, 
                {
                    "name": "Number of Records", 
                    "fieldIconRes": "number-quant-cust", 
                    "isGenerated": true, 
                    "defaultFieldRole": "measure", 
                    "aggregation": "none", 
                    "defaultAggregation": "sum", 
                    "isAutoColumn": true, 
                    "fieldType": "quantitative", 
                    "fieldRole": "measure", 
                    "type": "column", 
                    "defaultFieldType": "quantitative", 
                    "fn": "[Sample - Coffee Chain (Access)].[Number of Records]", 
                    "description": "Number of Records"
                }
            ], 
            "name": "Sample - Coffee Chain (Access)", 
            "datasourceCaption": "Sample - Coffee Chain (Access)", 
            "fieldIconRes": "datasource"
        }
    ], 
    "parametersDatasource": "Parameters"
}